language: go

go:
 - 1.4.2

matrix:
  fast_finish: true
env:
  global:
   - secure: VIEjEXaqVROZxJElghr9ZySHy0JPv8N9Saeb2exAYnbDevlh40OWR24z1IhyGYgx/ApIkLBmvRcybLsvG9WG7CRVNdmt1d1wPfBbGdsDluvtGlsGAT8n+giSBfQhwnN99G+GhWAvx9wIzZ/Gr1HLe2H4EHF7oOuYu720IYeSKBw=
   - GOBIN=$HOME/bin
   - PATH=$HOME/bin:$PATH

install:
 - go get golang.org/x/tools/cmd/vet golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover
 - go get -t -v ./...

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
 - go list -f '{{if len .TestGoFiles}}go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}{{end}}' ./... | xargs -i sh -c {}
 - gover
 - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
