language: go
go:
- 1.3
- tip
matrix:
  fast_finish: true
env:
  global:
    secure: VIEjEXaqVROZxJElghr9ZySHy0JPv8N9Saeb2exAYnbDevlh40OWR24z1IhyGYgx/ApIkLBmvRcybLsvG9WG7CRVNdmt1d1wPfBbGdsDluvtGlsGAT8n+giSBfQhwnN99G+GhWAvx9wIzZ/Gr1HLe2H4EHF7oOuYu720IYeSKBw=
install:
- export GOBIN=$HOME/bin
- export PATH=$GOBIN:$PATH
- go get code.google.com/p/go.tools/cmd/vet code.google.com/p/go.tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover
- go get -t -v ./...
- go install -a -race std
script:
- go tool vet -all .
- go build ./...
- go test -race -v ./...
- gover
- goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
